# Generated by Django 2.1.5 on 2019-01-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dblearning',
            name='salary',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dblearning',
            name='worked',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dbpred',
            name='salary',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dbpred',
            name='worked',
            field=models.FloatField(max_length=100),
        ),
    ]
