# Generated by Django 2.1.5 on 2019-01-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190108_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundColor', models.CharField(max_length=20)),
                ('borderColor', models.CharField(max_length=20)),
            ],
        ),
    ]
