# Generated by Django 2.1.5 on 2019-01-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190113_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='color',
            new_name='chartColor',
        ),
    ]
