# Generated by Django 2.1.5 on 2019-01-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190113_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartcolor',
            name='backgroundColor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='chartcolor',
            name='borderColor',
            field=models.CharField(max_length=40),
        ),
    ]
